on: push
name: deploy
jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build and push to docker
        uses: docker/build-push-action@v2
        with:
          username: "ellyesp"
          password: "DonkeyKong123"
          repository: "ellyesp/nintendon-t"
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}